### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ghost** [hjohn/Carousel#2]
Hey we were going to use this for a school related project. Could you add a license so we could use it? Thanks a bunch!

**Comment by hjohn** [comment]
I've added the BSD license to the master branch.  There's also a JavaFX 8 branch (not backwards compatible) that has been significantly changed (and cleaned) but it will eventually get the same license.

I hope the code will be of some use, I intend to improve it further once Java 8 is released and turn it into a standard control.
